# ### dotnet-lib-cd
# #### source: dotnet-lib
name: CD

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    name: Publish to NuGet
    permissions:
      contents: read
    uses: ./.github/workflows/⚡reusable-publish.yaml
    secrets: inherit
