# ### workspace-ci
# #### source: workspace
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  precommit:
    name: Pre-Commit
    permissions:
      contents: read
    uses: ./.github/workflows/⚡reusable-precommit.yaml
    secrets: inherit

  # ### dotnet-base-ci
  # #### source: dotnet-base
  deadcode:
    name: Dead Code
    permissions:
      contents: read
    uses: ./.github/workflows/⚡reusable-dead-code.yaml
    secrets: inherit

  unit:
    name: Unit Tests
    permissions:
      contents: read
    uses: ./.github/workflows/⚡reusable-test.yaml
    secrets: inherit
    with:
      mode: unit
      name: Unit

  int:
    name: Integration Tests
    permissions:
      contents: read
    uses: ./.github/workflows/⚡reusable-test.yaml
    secrets: inherit
    with:
      mode: int
      name: Integration

  # ### dotnet-lib-ci
  # #### source: dotnet-lib
  meta:
    name: TestHelper Meta Tests
    permissions:
      contents: read
    uses: ./.github/workflows/⚡reusable-test.yaml
    secrets: inherit
    with:
      mode: meta
      name: TestHelper Meta

  package-validate:
    name: Package Validation
    permissions:
      contents: read
    uses: ./.github/workflows/⚡reusable-package-validate.yaml
    secrets: inherit

  build:
    name: Build
    permissions:
      contents: read
    uses: ./.github/workflows/⚡reusable-build.yaml
    secrets: inherit
